apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mycelium-operator
  name: mycelium-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycelium-operator
  template:
    metadata:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: mycelium-operator
    spec:
      containers:
        - name: operator
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          image: {{ tpl $.Values.images.operator $ }}
          env:
            - name: MYCELIUM_FW_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mycelium-operator
                  key: forwarding_token
            - name: MYCELIUM_ENDPOINT
              value: mycelium-operator.{{ .Release.Namespace }}.svc.cluster.local:8080
            - name: MYCELIUM_RUNNER_IMAGE
              value: {{ tpl $.Values.images.runner $ }}
            - name: MYCELIUM_PLUGIN_VELOCITY
              value: {{ tpl $.Values.plugins.mycelium.velocity $ }}
            - name: MYCELIUM_PLUGIN_PAPER
              value: {{ tpl $.Values.plugins.mycelium.paper $ }}
            - name: METRICS_PLUGIN_VELOCITY
              value: {{ tpl $.Values.plugins.metrics.velocity $ }}
            - name: METRICS_PLUGIN_PAPER
              value: {{ tpl $.Values.plugins.metrics.paper $ }}
          ports:
            - containerPort: 8080
              name: api
          readinessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      serviceAccountName: mycelium-operator
