---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mycelium-operator
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mycelium-operator
rules:
  - apiGroups: ["mycelium.njha.dev"]
    resources: ["*"]
    verbs: ["*"]
  # TODO: Can we restrict this to only children of mycelium CRDs?
  - apiGroups: ["*"]
    resources: ["statefulsets", "services", "events", "secrets", "poddisruptionbudgets"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mycelium-operator
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: mycelium-operator
roleRef:
  kind: ClusterRole
  name: mycelium-operator
  apiGroup: rbac.authorization.k8s.io